/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalprogra3;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author H P
 */
public class CarreraDeTortugas extends javax.swing.JFrame {

    /**
     * Creates new form CarreraDeTortugas
     */
    ArrayList<String> palabras = new ArrayList<>();
    ArrayList<String> significados = new ArrayList<>();
    public CarreraDeTortugas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnjugar = new javax.swing.JButton();
        panelpista = new javax.swing.JPanel();
        lbtortuga = new javax.swing.JLabel();
        lbpista = new javax.swing.JLabel();
        tfrespuesta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btncalificar = new javax.swing.JButton();
        tfpalabra = new javax.swing.JTextField();
        tfcorrect = new javax.swing.JTextField();
        btnregresar = new javax.swing.JButton();
        tfvidas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btnjugar.setText("Jugar");
        btnjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjugarActionPerformed(evt);
            }
        });

        panelpista.setBackground(new java.awt.Color(255, 255, 255));

        lbtortuga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tortuga.jpg"))); // NOI18N

        lbpista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/meta.jpg"))); // NOI18N

        javax.swing.GroupLayout panelpistaLayout = new javax.swing.GroupLayout(panelpista);
        panelpista.setLayout(panelpistaLayout);
        panelpistaLayout.setHorizontalGroup(
            panelpistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpistaLayout.createSequentialGroup()
                .addComponent(lbtortuga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbpista, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelpistaLayout.setVerticalGroup(
            panelpistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpistaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbtortuga)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpistaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbpista))
        );

        tfrespuesta.setBackground(new java.awt.Color(204, 255, 204));
        tfrespuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfrespuesta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ingresa la traduccion correcta: ");

        btncalificar.setText("Calificar");
        btncalificar.setEnabled(false);
        btncalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalificarActionPerformed(evt);
            }
        });

        tfpalabra.setBackground(new java.awt.Color(204, 255, 204));
        tfpalabra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfpalabra.setText("Palabra");
        tfpalabra.setBorder(null);
        tfpalabra.setEnabled(false);

        tfcorrect.setBackground(new java.awt.Color(204, 255, 204));
        tfcorrect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfcorrect.setText("Respuesta");
        tfcorrect.setBorder(null);
        tfcorrect.setEnabled(false);

        btnregresar.setText("Regresar al menu");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        tfvidas.setBackground(new java.awt.Color(204, 255, 204));
        tfvidas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfvidas.setBorder(null);
        tfvidas.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnjugar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnregresar))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfvidas, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addGap(162, 162, 162)
                .addComponent(btncalificar)
                .addGap(268, 268, 268))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfpalabra, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(tfrespuesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfcorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelpista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnjugar)
                    .addComponent(btnregresar))
                .addGap(48, 48, 48)
                .addComponent(panelpista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfpalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(tfcorrect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btncalificar))
                    .addComponent(tfvidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x=0;
    int y=90;
    int aux=1;
    int vidas=3;
    private void btnjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjugarActionPerformed
        // TODO add your handling code here:
        btncalificar.setEnabled(true);
        palabras.add("cihuatl");//esposa o mujer
        palabras.add("colli");//anciano o abuelo
         palabras.add("piltzintli");//bebe
         palabras.add("oquichtli");//hombre
         palabras.add("temachtiani"); //profesor, maestro
         palabras.add("tlahtoani");//: gobernante
         significados.add("esposa");
         significados.add("anciano");
         significados.add("bebe");
         significados.add("hombre");
         significados.add("profesor");
         significados.add("gobernante");
         String pal=(String) significados.toArray()[0];
         tfpalabra.setText(pal);
         String vid="Vidas: ";
         
        for (int i = 0; i < vidas; i++) {
            vid=vid.concat("*");
        }
        tfvidas.setText(vid);
    }//GEN-LAST:event_btnjugarActionPerformed
    
    private void btncalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalificarActionPerformed
        // TODO add your handling code here:
        btnjugar.setEnabled(false);
        String sig="";
        String palabra=(String) palabras.toArray()[aux-1];
        if(palabra.equalsIgnoreCase(tfrespuesta.getText())){
            
            x=x+100;
            lbtortuga.setLocation(x, y);
            tfcorrect.setText("!Correcto¡");
            String pal=(String) palabras.toArray()[aux];
            aux++;
            
        }else{
            tfcorrect.setText("!Incorrecto¡");
            aux++;
            vidas--;
            if(vidas==0){
                    JOptionPane.showMessageDialog(null,"Juegos Terminado");
                    MenuPrincipal n=new MenuPrincipal();
                     n.setVisible(true);
                    this.setVisible(false);
                }
        }
        if(x>=500){
            JOptionPane.showMessageDialog(null,"Felicidades Ganaste");
            MenuPrincipal a=new MenuPrincipal();
                a.setVisible(true);
                this.setVisible(false);
        }
        sig=(String) significados.toArray()[aux-1];
        tfpalabra.setText(sig);
         String vid="Vidas: ";
         
        for (int i = 0; i < vidas; i++) {
            vid=vid.concat("*");
        }
        tfvidas.setText(vid);
        System.out.println(x);
    }//GEN-LAST:event_btncalificarActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:
        MenuPrincipal n=new MenuPrincipal();
                n.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_btnregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalificar;
    private javax.swing.JButton btnjugar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbpista;
    private javax.swing.JLabel lbtortuga;
    private javax.swing.JPanel panelpista;
    private javax.swing.JTextField tfcorrect;
    private javax.swing.JTextField tfpalabra;
    private javax.swing.JTextField tfrespuesta;
    private javax.swing.JTextField tfvidas;
    // End of variables declaration//GEN-END:variables
}
