/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalprogra3;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author H P
 */
public class EnsaladaDeLetras extends javax.swing.JFrame {

    /**
     * Creates new form EnsaladaDeLetras
     */
    public EnsaladaDeLetras() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    ArrayList<String> palabras = new ArrayList<>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        tfrespuesta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbpalabra = new javax.swing.JLabel();
        btnjugar = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();
        btncalificar = new javax.swing.JButton();
        lbpuntos = new javax.swing.JLabel();
        lbvidas = new javax.swing.JLabel();
        lbimagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(java.awt.Color.cyan);

        tfrespuesta.setBackground(new java.awt.Color(153, 0, 204));
        tfrespuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfrespuesta.setForeground(new java.awt.Color(255, 255, 255));
        tfrespuesta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));
        tfrespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfrespuestaActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresa la palabra de manera correcta");

        lbpalabra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbpalabra.setForeground(new java.awt.Color(204, 0, 204));
        lbpalabra.setText("Palabra");

        btnjugar.setBackground(new java.awt.Color(255, 255, 255));
        btnjugar.setForeground(new java.awt.Color(51, 51, 255));
        btnjugar.setText("Jugar");
        btnjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjugarActionPerformed(evt);
            }
        });

        btnregresar.setBackground(new java.awt.Color(255, 255, 255));
        btnregresar.setForeground(new java.awt.Color(51, 51, 255));
        btnregresar.setText("Regresar al menu");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        btncalificar.setBackground(new java.awt.Color(255, 255, 255));
        btncalificar.setForeground(new java.awt.Color(51, 51, 255));
        btncalificar.setText("Calificar");
        btncalificar.setEnabled(false);
        btncalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalificarActionPerformed(evt);
            }
        });

        lbpuntos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbpuntos.setForeground(new java.awt.Color(204, 0, 204));
        lbpuntos.setText("Puntos: ");

        lbvidas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbvidas.setForeground(new java.awt.Color(204, 0, 204));
        lbvidas.setText("Vidas: ");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(btnjugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnregresar))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(lbpuntos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncalificar)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(tfrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(190, 190, 190))))
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(lbpalabra))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbvidas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 185, Short.MAX_VALUE)
                .addComponent(lbimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnjugar)
                    .addComponent(btnregresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(lbimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbpalabra)
                .addGap(41, 41, 41)
                .addComponent(tfrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btncalificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(lbpuntos)
                        .addGap(22, 22, 22)))
                .addComponent(lbvidas)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfrespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfrespuestaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfrespuestaActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:
        MenuPrincipal n=new MenuPrincipal();
                n.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_btnregresarActionPerformed

    private void btnjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjugarActionPerformed
        // TODO add your handling code here:
        btncalificar.setEnabled(true);
        palabras.add("cihuatl");//esposa o mujer
        palabras.add("colli");//anciano o abuelo
         palabras.add("piltzintli");//bebe
         palabras.add("oquichtli");//hombre
         Graphics papel=panel.getGraphics();
         papel.setColor(Color.WHITE);
         
         //papel.setColor(Color.CYAN);
         String pal=(String) palabras.toArray()[0];
         ImageIcon foto;
         foto=new ImageIcon(getClass().getResource("/imagenes/"+pal+".jpg"));
         lbimagen.setIcon(foto);
         String palmix="";
         int tam=pal.length();
         ArrayList<Integer> nums = new ArrayList<>(tam);
         for(int i=0;i<tam;i++){
             nums.add(-1);
         }
         char let;
         String aux;
           int indice;
         for(int i=0;i<tam;){
             indice = (int) Math.floor(Math.random()*((tam-1)-0+1)+0);
             if(numrep(indice,tam,nums)==0){
                 let=pal.charAt(indice);
                 aux=Character.toString(let);
                 palmix=palmix.concat(aux);
                 nums.set(i++,indice);
             }
         }
         lbpalabra.setText(palmix);
         lbpuntos.setText("Puntos: "+puntos);
        String vid="Vidas: ";
         
        for (int i = 0; i < vidas; i++) {
            vid=vid.concat("*");
        }
        lbvidas.setText(vid);
    }//GEN-LAST:event_btnjugarActionPerformed
    int x=1;//este controla
    int puntos=0;//este es el puntaje
    int vidas=3;
    private void btncalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalificarActionPerformed
        // TODO add your handling code here:
        btnjugar.setEnabled(false);
        
        String palabra=(String) palabras.toArray()[x-1];
        if(palabra.equalsIgnoreCase(tfrespuesta.getText())){
            puntos=puntos+10;
            JOptionPane.showMessageDialog(null,"Respuesta Correcta");
            String pal=(String) palabras.toArray()[x];
            ImageIcon foto;
             foto=new ImageIcon(getClass().getResource("/imagenes/"+pal+".jpg"));
            lbimagen.setIcon(foto);
            String palmix="";
            int tam=pal.length();
            ArrayList<Integer> nums = new ArrayList<>(tam);
            for(int i=0;i<tam;i++){
                 nums.add(-1);
            }
            char let;
            String aux;
            int indice;
            for(int i=0;i<tam;){
                 indice = (int) Math.floor(Math.random()*((tam-1)-0+1)+0);
                if(numrep(indice,tam,nums)==0){
                     let=pal.charAt(indice);
                    aux=Character.toString(let);
                    palmix=palmix.concat(aux);
                    nums.set(i++,indice);
                }
            }
            lbpalabra.setText(palmix);
            x++;
         }else{
                JOptionPane.showMessageDialog(null,"Respuesta Incorrecta,intentalo de nuevo");
                vidas--;
                if(vidas==0){
                    JOptionPane.showMessageDialog(null,"Juegos Terminado");
                    MenuPrincipal n=new MenuPrincipal();
                     n.setVisible(true);
                    this.setVisible(false);
                }
        }
        lbpuntos.setText("Puntos: "+puntos);
        String vid="Vidas: ";
         
        for (int i = 0; i < vidas; i++) {
            vid=vid.concat("*");
        }
        lbvidas.setText(vid);
    }//GEN-LAST:event_btncalificarActionPerformed
    static int numrep(int num,int tam,ArrayList nums){
        int i=0,repe=0;
        int aux=0;
        for(i=0;i<tam;i++){
            aux=(int) nums.toArray()[i];
            if(aux==num){
                repe=1;
            }
        }
        return repe;
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalificar;
    private javax.swing.JButton btnjugar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbimagen;
    private javax.swing.JLabel lbpalabra;
    private javax.swing.JLabel lbpuntos;
    private javax.swing.JLabel lbvidas;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tfrespuesta;
    // End of variables declaration//GEN-END:variables
}
